# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicity', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('residency', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('headcount', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
