# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactivechart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admitted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Applied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='enrolled',
            name='stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactivechart.Student'),
        ),
        migrations.AddField(
            model_name='applied',
            name='stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactivechart.Student'),
        ),
        migrations.AddField(
            model_name='admitted',
            name='stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactivechart.Student'),
        ),
    ]
