# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactivechart', '0002_auto_20170331_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(max_length=20),
        ),
    ]
